## AUTO-GENERATED by tools/generate_cards.ts — DO NOT EDIT MANUALLY
## Source of truth: data/cards.json
## CardDatabase — loads card definitions from .tres resource files.
class_name CardDatabase
extends RefCounted

const CARDS_DIR := "res://data/cards/"
const AbilityScript = preload("res://scripts/abilities/ability.gd")
const AbilityTriggerScript = preload("res://scripts/abilities/trigger.gd")
const AbilityTargetScript = preload("res://scripts/abilities/target.gd")
const EffectStepScript = preload("res://scripts/abilities/effect_step.gd")
const CharacterCardScript = preload("res://scripts/cards/character_card.gd")
const UnitCardScript = preload("res://scripts/cards/unit_card.gd")
const SpellCardScript = preload("res://scripts/cards/spell_card.gd")

const BUILTIN_CARDS := [
	preload("res://data/cards/explodus.tres"),
	preload("res://data/cards/bodur.tres"),
	preload("res://data/cards/torzs_zullott.tres"),
	preload("res://data/cards/griff.tres"),
	preload("res://data/cards/zsalu.tres"),
	preload("res://data/cards/altus.tres"),
	preload("res://data/cards/mandur.tres"),
	preload("res://data/cards/felix.tres"),
	preload("res://data/cards/fetus.tres"),
	preload("res://data/cards/cassanus.tres"),
	preload("res://data/cards/artifex.tres"),
	preload("res://data/cards/fuedrax.tres"),
	preload("res://data/cards/ezethriel.tres"),
	preload("res://data/cards/elfina.tres"),
	preload("res://data/cards/guner.tres"),
	preload("res://data/cards/x_mizuki_kiralyno.tres"),
	preload("res://data/cards/nixie.tres"),
	preload("res://data/cards/caecus.tres"),
	preload("res://data/cards/matroz.tres"),
	preload("res://data/cards/hektor.tres"),
	preload("res://data/cards/barkakedvenc.tres"),
	preload("res://data/cards/pirato_sanchez.tres"),
	preload("res://data/cards/luna_kapitany.tres"),
	preload("res://data/cards/arnyekurno.tres"),
	preload("res://data/cards/papagaj.tres"),
	preload("res://data/cards/embercsempesz.tres"),
	preload("res://data/cards/kapzsi_kisertet.tres"),
	preload("res://data/cards/ryan_cooper.tres"),
	preload("res://data/cards/bolyongo.tres"),
	preload("res://data/cards/ouroboros.tres"),
	preload("res://data/cards/hjaflgar.tres"),
	preload("res://data/cards/mashu_liderc.tres"),
	preload("res://data/cards/ambiciosus_paleontologus.tres"),
	preload("res://data/cards/oshullo.tres"),
	preload("res://data/cards/explar.tres"),
	preload("res://data/cards/tor.tres"),
	preload("res://data/cards/mozgositas.tres"),
	preload("res://data/cards/villamhaboru.tres"),
	preload("res://data/cards/gyorshitel.tres"),
	preload("res://data/cards/lesbol_tamadas.tres"),
	preload("res://data/cards/ujraelosztas.tres"),
	preload("res://data/cards/hatarzar.tres"),
	preload("res://data/cards/all_in.tres"),
	preload("res://data/cards/lomtalanitas.tres"),
	preload("res://data/cards/hamiskartya.tres"),
	preload("res://data/cards/elcsenes.tres"),
	preload("res://data/cards/arurakodas.tres"),
	preload("res://data/cards/rozzant_granat.tres"),
	preload("res://data/cards/suttogavatas.tres"),
	preload("res://data/cards/a_gomb.tres"),
]

static var _cards: Dictionary = {}
static var _initialized: bool = false

static func init() -> void:
	if _initialized:
		return
	_initialized = true
	_load_cards()

static func get_card(id: int):
	init()
	if _cards.has(id):
		return _cards[id].duplicate()
	return null

static func get_all_cards() -> Array:
	init()
	return _cards.values().duplicate()

static func _load_cards() -> void:
	_cards.clear()
	for card in BUILTIN_CARDS:
		if card and card.get("card_id"):
			_cards[card.card_id] = card
	var dir := DirAccess.open(CARDS_DIR)
	if not dir:
		push_warning("CardDatabase: Cannot open %s, using preloaded cards only." % CARDS_DIR)
		print("CardDatabase: Loaded %d cards (preloaded only)." % _cards.size())
		return
	dir.list_dir_begin()
	var file_name := dir.get_next()
	while file_name != "":
		if not dir.current_is_dir() and file_name.ends_with(".tres"):
			var p := CARDS_DIR + file_name
			var card = load(p)
			if card and card.get("card_id"):
				_cards[card.card_id] = card
			else:
				push_warning("CardDatabase: Skipped %s (no card_id)" % p)
		file_name = dir.get_next()
	dir.list_dir_end()
	_ensure_fallback_cards()
	print("CardDatabase: Loaded %d cards." % _cards.size())

static func _new_trigger(event: String, params: Dictionary = {}) -> AbilityTriggerScript:
	var t = AbilityTriggerScript.new()
	t.event = event
	for key in params:
		t.set(key, params[key])
	return t

static func _new_target(target_type: String, owner: String, targeting: String, params: Dictionary = {}) -> AbilityTargetScript:
	var tgt = AbilityTargetScript.new()
	tgt.target_type = target_type
	tgt.owner = owner
	tgt.targeting = targeting
	for key in params:
		tgt.set(key, params[key])
	return tgt

static func _new_effect(step: String, params: Dictionary = {}) -> EffectStepScript:
	var e = EffectStepScript.new()
	e.step = step
	for key in params:
		if key == "parameters":
			e.parameters = params[key]
		elif key == "sub_effects" or key == "else_effects" or key == "choices":
			continue
		else:
			e.set(key, params[key])
	return e

static func _new_ability(ability_name: String, description: String, trigger: AbilityTriggerScript, targets: Array = [], effects: Array = []) -> AbilityScript:
	var ab = AbilityScript.new()
	ab.ability_name = ability_name
	ab.description = description
	ab.trigger = trigger
	ab.targets = targets
	ab.effects = effects
	return ab

static func _ensure_fallback_cards() -> void:
	if not _cards.has(1001):
		_cards[1001] = _build_explodus()
	if not _cards.has(1002):
		_cards[1002] = _build_bodur()
	if not _cards.has(1003):
		_cards[1003] = _build_torzs_zullott()
	if not _cards.has(1004):
		_cards[1004] = _build_griff()
	if not _cards.has(1005):
		_cards[1005] = _build_zsalu()
	if not _cards.has(1006):
		_cards[1006] = _build_altus()
	if not _cards.has(1007):
		_cards[1007] = _build_mandur()
	if not _cards.has(1008):
		_cards[1008] = _build_felix()
	if not _cards.has(1009):
		_cards[1009] = _build_fetus()
	if not _cards.has(1010):
		_cards[1010] = _build_cassanus()
	if not _cards.has(1011):
		_cards[1011] = _build_artifex()
	if not _cards.has(1012):
		_cards[1012] = _build_fuedrax()
	if not _cards.has(1013):
		_cards[1013] = _build_ezethriel()
	if not _cards.has(1014):
		_cards[1014] = _build_elfina()
	if not _cards.has(1015):
		_cards[1015] = _build_guner()
	if not _cards.has(1016):
		_cards[1016] = _build_x_mizuki_kiralyno()
	if not _cards.has(1017):
		_cards[1017] = _build_nixie()
	if not _cards.has(2001):
		_cards[2001] = _build_caecus()
	if not _cards.has(2002):
		_cards[2002] = _build_matroz()
	if not _cards.has(2003):
		_cards[2003] = _build_hektor()
	if not _cards.has(2004):
		_cards[2004] = _build_barkakedvenc()
	if not _cards.has(2005):
		_cards[2005] = _build_pirato_sanchez()
	if not _cards.has(2006):
		_cards[2006] = _build_luna_kapitany()
	if not _cards.has(2007):
		_cards[2007] = _build_arnyekurno()
	if not _cards.has(2008):
		_cards[2008] = _build_papagaj()
	if not _cards.has(2009):
		_cards[2009] = _build_embercsempesz()
	if not _cards.has(2010):
		_cards[2010] = _build_kapzsi_kisertet()
	if not _cards.has(2011):
		_cards[2011] = _build_ryan_cooper()
	if not _cards.has(2012):
		_cards[2012] = _build_bolyongo()
	if not _cards.has(2013):
		_cards[2013] = _build_ouroboros()
	if not _cards.has(2014):
		_cards[2014] = _build_hjaflgar()
	if not _cards.has(2015):
		_cards[2015] = _build_mashu_liderc()
	if not _cards.has(2016):
		_cards[2016] = _build_ambiciosus_paleontologus()
	if not _cards.has(2017):
		_cards[2017] = _build_oshullo()
	if not _cards.has(3001):
		_cards[3001] = _build_explar()
	if not _cards.has(3002):
		_cards[3002] = _build_tor()
	if not _cards.has(3003):
		_cards[3003] = _build_mozgositas()
	if not _cards.has(3004):
		_cards[3004] = _build_villamhaboru()
	if not _cards.has(3005):
		_cards[3005] = _build_gyorshitel()
	if not _cards.has(3006):
		_cards[3006] = _build_lesbol_tamadas()
	if not _cards.has(3007):
		_cards[3007] = _build_ujraelosztas()
	if not _cards.has(3008):
		_cards[3008] = _build_hatarzar()
	if not _cards.has(3009):
		_cards[3009] = _build_all_in()
	if not _cards.has(3010):
		_cards[3010] = _build_lomtalanitas()
	if not _cards.has(3011):
		_cards[3011] = _build_hamiskartya()
	if not _cards.has(3012):
		_cards[3012] = _build_elcsenes()
	if not _cards.has(3013):
		_cards[3013] = _build_arurakodas()
	if not _cards.has(3014):
		_cards[3014] = _build_rozzant_granat()
	if not _cards.has(3015):
		_cards[3015] = _build_suttogavatas()
	if not _cards.has(4001):
		_cards[4001] = _build_a_gomb()

static func _build_explodus():
	var t0 = _new_trigger("ON_PLAY", {"modifier1": "ALLY", "modifier2": "Spell", "trigger_interactors": {"PlayedCard": "tag:Tűz"}})
	var t1 = _new_target("Card", "Ally", "Automatic")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "ModifyAmount": -1, "ModifyDuration": 4}, "target_ref": "targets[0]"})
	var e3 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "DAMAGE_BONUS", "ModifyAmount": 1, "ModifyDuration": 4}, "target_ref": "targets[0]"})
	var e4 = _new_effect("", {"flow": {"type": "choose_one"}})
	e4.choices = [{"label": "Tűz Kedvezmény: 1-gyel kevesebbe kerül", "effects": [e2]}, {"label": "Tűz Erősítés: 1-gyel több sebzést okoz", "effects": [e3]}]
	var main_ab = _new_ability("Néma Tüzek", "Amikor kijátszol egy Tűz varázslatot, válassz egyet.", t0, [t1], [e4])
	var card = CharacterCardScript.new()
	card.card_id = 1001
	card.card_name = "Explodus"
	card.card_class = "Mágus"
	card.title = "a Néma Tüzek Őre"
	card.description = "Amikor kijátszol egy Tűz varázslatot, válassz: 1-gyel kevesebbe kerül, VAGY 1-gyel több sebzést okoz."
	card.abilities = [main_ab]
	return card

static func _build_bodur():
	var t0 = _new_trigger("ON_PLAY", {"modifier1": "ALLY", "modifier2": "Unit"})
	var t1 = _new_target("Unit", "Ally", "PlayerChoice", {"condition": "cost<PlayedCard.cost", "prompt": "Adj parancsot egy egységnek!"})
	var e2 = _new_effect("MakeAttack", {"target_ref": "targets[0]"})
	var e3 = _new_effect("Move", {"parameters": {"MoveAmount": 1}, "target_ref": "targets[0]"})
	var e4 = _new_effect("", {"flow": {"type": "choose_one"}})
	e4.choices = [{"label": "Támadás: Az egység újratámad", "effects": [e2]}, {"label": "Mozgás: Az egység mozog egy mezőt", "effects": [e3]}]
	var main_ab = _new_ability("Parancs", "Adj parancsot egy kisebb alapköltségű szövetségesnek!", t0, [t1], [e4])
	var card = CharacterCardScript.new()
	card.card_id = 1002
	card.card_name = "Bodur Kapitány"
	card.card_class = "Harcos"
	card.title = "a Veterán Parancsnok"
	card.description = "Amikor kijátszol egy egységet, adj egy parancsot egy kisebb alapköltségű szövetségesnek!
Támadás: Az egység újratámad.
Mozgás: Az egység mozog egy mezőt."
	card.abilities = [main_ab]
	return card

static func _build_torzs_zullott():
	var t0 = _new_trigger("ON_KILL", {"modifier1": "ALLY", "modifier2": "Unit", "trigger_interactors": {"KillingUnit": "tag:Kalóz"}})
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var t2 = _new_target("Player", "Ally", "Automatic")
	var e3 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}, "target_ref": "targets[0]"})
	var e4 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Ring", "ModifyAmount": 1}, "target_ref": "targets[1]"})
	var main_ab = _new_ability("Kalóz Zsákmány", "Miután egy szövetséges Kalóz megöl egy ellenséges egységet, húzz egy gyűrűt és egy lapot!", t0, [t1, t2], [e3, e4])
	var card = CharacterCardScript.new()
	card.card_id = 1003
	card.card_name = "Torzs-züllödt"
	card.card_class = "Zsivány"
	card.title = "a Vörös-Folyam Réme"
	card.description = "Miután egy szövetséges Kalóz megöl egy ellenséges egységet, húzz egy gyűrűt és egy lapot!"
	card.abilities = [main_ab]
	return card

static func _build_griff():
	var t0 = _new_trigger("ON_DISCARDED", {"modifier1": "ALLY", "limit_type": "PER_TURN", "limit_count": 1})
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var e2 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Hamiskártyás Ász", "Amikor egy körben először dobsz el egy lapot, húzz egy lapot!", t0, [t1], [e2])
	var card = CharacterCardScript.new()
	card.card_id = 1004
	card.card_name = "Griff"
	card.card_class = "Garabonciás"
	card.title = "a Hamiskártyás"
	card.description = "Amikor egy körben először dobsz el egy lapot, húzz egy lapot!"
	card.abilities = [main_ab]
	return card

static func _build_zsalu():
	var t0 = _new_trigger("CONTINUOUS")
	var t1 = _new_target("Card", "Ally", "AllValid", {"condition": "has_tag:stolen"})
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "ModifyAmount": -2, "ModifyDuration": 0}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Tolvaj Mesterség", "Az általad rabolt lapok 2-vel kevesebbe kerülnek.", t0, [t1], [e2])
	var card = CharacterCardScript.new()
	card.card_id = 1005
	card.card_name = "Zsalu"
	card.card_class = "Zsivány"
	card.title = "a Tolvaj Geci"
	card.description = "Rablás: Az általad rabolt lapok 2-vel kevesebbe kerülnek."
	card.abilities = [main_ab]
	return card

static func _build_altus():
	var t0 = _new_trigger("CONTINUOUS")
	var t1 = _new_target("Unit", "Ally", "AllValid", {"condition": "cost<=2"})
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "ATK", "ModifyAmount": 1, "ModifyDuration": 0}, "target_ref": "targets[0]"})
	var ab0 = _new_ability("Raj", "Minden szövetséges egység, amelynek a költsége maximum (2), +1-gyel támad.", t0, [t1], [e2])
	var t3 = _new_trigger("ON_TURN_END", {"game_state_condition": "ally_hand_count == 0"})
	var t4 = _new_target("Deck", "Ally", "Automatic")
	var e5 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}})
	var ab1 = _new_ability("Utánpótlás", "Alkony: Ha üres a kezed, húzz egy lapot!", t3, [t4], [e5])
	var card = CharacterCardScript.new()
	card.card_id = 1006
	card.card_name = "Altus"
	card.card_class = "Vaják"
	card.title = "a Raj Mestere"
	card.description = "Minden szövetséges egység, amelynek a költsége maximum (2), +1-gyel támad.

Alkony: Ha üres a kezed, húzz egy lapot."
	card.abilities = [ab0, ab1]
	return card

static func _build_mandur():
	var t0 = _new_trigger("ACTIVATED")
	var t1 = _new_target("Graveyard", "Ally", "Automatic")
	var e2 = _new_effect("Search", {"parameters": {"SelectAmount": "any", "Prompt": "Válassz lapokat a megsemmisítéshez!"}, "tag": "mandur_exile", "target_ref": "targets[0]"})
	var e3 = _new_effect("Exile", {"tag": "mandur_exiled", "target_ref": "mandur_exile.SelectedCards"})
	var e4 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "ModifyAmount": "-mandur_exiled.ExiledUnit/2", "ModifyDuration": 4, "ApplyFilter": "next_unit"}})
	var main_ab = _new_ability("Sírrablás", "Semmisíts meg lapokat az umbrádban és csökkentsd (1)-gyel a következőnek kijátszott egységed költségét minden második így megsemmisített egység után.", t0, [t1], [e2, e3, e4])
	var card = CharacterCardScript.new()
	card.card_id = 1007
	card.card_name = "Man Dur Amarth"
	card.card_class = "Garabonciás"
	card.title = "a Vérsuttogó"
	card.description = "Megsemmisíthetsz lapokat az umbrádban. Minden második így megsemmisített lap után csökkentsd (1)-gyel a következőnek kijátszott egységed költségét."
	card.abilities = [main_ab]
	return card

static func _build_felix():
	var t0 = _new_trigger("ACTIVATED")
	var t1 = _new_target("SideDeck", "Ally", "Automatic")
	var e2 = _new_effect("Search", {"parameters": {"SelectAmount": 1, "Prompt": "Válassz egységet a Segédpaklidból!"}, "tag": "portal", "target_ref": "targets[0]"})
	var e3 = _new_effect("PlayCard", {"parameters": {"ExtraCost": 1}, "target_ref": "portal.SelectedCards"})
	var main_ab = _new_ability("Portálnyitás", "(1) + a lap költsége: Játssz ki egy egységet a Segédpaklidból!", t0, [t1], [e2, e3])
	var card = CharacterCardScript.new()
	card.card_id = 1008
	card.card_name = "Felix"
	card.card_class = "Mágus"
	card.title = "a Hajnali Utas"
	card.deckbuilding_rules = {"sidedeck": {"max": 3, "filter": "type:UNIT,!class:Mágus"}}
	card.description = "A pakliépítésnél összeállíthatsz egy Segédpaklit három nem Mágus egységből.

(1) + a lap költsége: Nyiss egy portált és játssz ki onnan egy általad választott egységet!"
	card.abilities = [main_ab]
	return card

static func _build_fetus():
	var t0 = _new_trigger("CONTINUOUS")
	var t1 = _new_target("Unit", "Ally", "AllValid", {"condition": "tag:Sárkány,cost>=7"})
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "MOVE_SPEED", "ModifyAmount": 1, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var e3 = _new_effect("ModifyKeyword", {"parameters": {"AddedKeywords": ["Ütéselőny"], "NewKeywordDurations": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Sárkánylovas", "Passzív: A legalább (7) alapköltségű szövetséges Sárkányaid +1 mozgási sebességet és Ütéselőnyt kapnak.", t0, [t1], [e2, e3])
	var card = CharacterCardScript.new()
	card.card_id = 1009
	card.card_name = "Ƒetus"
	card.card_class = "Bölcs"
	card.title = "a Serpens Kalandor"
	card.deckbuilding_rules = {"cross_class_tags": ["Sárkány"], "cross_class_rules": [{"tag": "Sárkány", "type": "unit", "min_cost": 7}]}
	card.description = "A pakliépítésnél bármely rendből tehetsz Sárkány egységeket a paklidba.

Passzív: A legalább (7) alapköltségű szövetséges Sárkányaid +1 mozgási sebességet és Ütéselőnyt kapnak."
	card.abilities = [main_ab]
	return card

static func _build_cassanus():
	var card = CharacterCardScript.new()
	card.card_id = 1010
	card.card_name = "Cassanus"
	card.card_class = "Harcos"
	card.title = "a Halhatatlan Törzsfőnök"
	card.deckbuilding_rules = {"starting_bench_cards": [{"card_id": 4001}]}
	card.description = "A Gömbbel kezded a játékot."
	return card

static func _build_artifex():
	var card = CharacterCardScript.new()
	card.card_id = 1011
	card.card_name = "Artifex"
	card.card_class = "Mágus"
	card.title = "a Kódfejtő Könyvtáros"
	card.game_rules = {"starting_hand_size": 7, "max_hand_size": 13}
	card.description = "7 lappal kezded a játékot és maximum 13 lap lehet a kezedben."
	return card

static func _build_fuedrax():
	var t0 = _new_trigger("ON_PLAY", {"modifier1": "ALLY", "modifier2": "Spell", "game_state_condition": "ally_pile_type_count:TRAP>=1", "trigger_interactors": {"PlayedCard": "type:TRAP"}})
	var t1 = _new_target("Pile", "Ally", "Automatic")
	var e2 = _new_effect("Search", {"parameters": {"SearchFilters": "type:TRAP", "SelectAmount": 1, "Prompt": "Válassz egy Csapdát, amit felhúzol!"}, "tag": "chosen_trap", "target_ref": "targets[0]"})
	var e3 = _new_effect("MoveToZone", {"target_ref": "chosen_trap.SearchResults"})
	var e4 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "SetAmount": 0, "ModifyDuration": 0}, "target_ref": "chosen_trap.SearchResults"})
	var e5 = _new_effect("Search", {"parameters": {"SearchFilters": "type:TRAP", "SelectAmount": -1}, "tag": "remaining_traps", "target_ref": "targets[0]"})
	var e6 = _new_effect("Exile", {"target_ref": "remaining_traps.SearchResults"})
	var main_ab = _new_ability("Káosz Csapdák", "Ha két Csapdád van a rakáson, húzd fel az egyiket (költsége 0 lesz), a másik megsemmisül.", t0, [t1], [e2, e3, e4, e5, e6])
	var card = CharacterCardScript.new()
	card.card_id = 1012
	card.card_name = "Fuedrax"
	card.card_class = "Vaják"
	card.title = "a Káoszcsapdász"
	card.description = "Amikor kijátszol egy Csapda kártyát és van már másik Csapda a rakásodon, húzd fel az egyiket és a költsége 0 lesz. A másik megsemmisül."
	card.abilities = [main_ab]
	return card

static func _build_ezethriel():
	var t0 = _new_trigger("CONTINUOUS")
	var t1 = _new_target("Card", "Ally", "AllValid", {"condition": "type:NATURE_FORCE"})
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "RANGE", "ModifyAmount": 1, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var e3 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "ModifyAmount": -1, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var ab0 = _new_ability("Természet Mestere", "Természeti erő kártyáid +1 hatótáv és -1 költség.", t0, [t1], [e2, e3])
	var t4 = _new_trigger("CONTINUOUS")
	var t5 = _new_target("Unit", "Ally", "AllValid", {"condition": "tag:Druida"})
	var e6 = _new_effect("ModifyKeyword", {"parameters": {"AddedKeywords": ["NatureForceImmunity"], "NewKeywordDurations": 1}, "target_ref": "targets[0]"})
	var ab1 = _new_ability("Druida Harmónia", "Szövetséges Druida egységeid ignorálják a negatív Természeti erő hatásokat.", t4, [t5], [e6])
	var card = CharacterCardScript.new()
	card.card_id = 1013
	card.card_name = "Ezethriel"
	card.card_class = "Vaják"
	card.title = "az Alapító"
	card.description = "A Természeti erőidnek +1 a hatótávja és (1)-gyel kevesebb a költsége. A szövetséges Druida egységeid ignorálják a negatív Természeti erő hatásokat."
	card.abilities = [ab0, ab1]
	return card

static func _build_elfina():
	var t0 = _new_trigger("CONTINUOUS")
	var t1 = _new_target("Unit", "Ally", "AllValid")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "MOVE_SPEED", "ModifyAmount": 1, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var ab0 = _new_ability("Természet Hívása", "Minden szövetséges egységnek +1 mozgási sebesség.", t0, [t1], [e2])
	var t3 = _new_trigger("CONTINUOUS")
	var t4 = _new_target("Unit", "Ally", "AllValid", {"condition": "tag:Állat|Druida"})
	var e5 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "MOVE_SPEED", "ModifyAmount": 1, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var ab1 = _new_ability("Vad Összeköttetés", "Szövetséges Állat és Druida egységeknek további +1 mozgási sebesség (+2 összesen).", t3, [t4], [e5])
	var card = CharacterCardScript.new()
	card.card_id = 1014
	card.card_name = "Elfina"
	card.card_class = "Vaják"
	card.title = "a Rókapapnő"
	card.description = "Minden szövetséges egységnek +1 mozgási sebesség. Állatoknak és Druidáknak +2."
	card.abilities = [ab0, ab1]
	return card

static func _build_guner():
	var t0 = _new_trigger("ON_ATTACK", {"modifier1": "ALLY"})
	var t1 = _new_target("Unit", "Ally", "Automatic", {"trigger_interactor": "AttackingUnit"})
	var e2 = _new_effect("", {"flow": {"type": "conditional", "condition": "attack_direction:rear"}})
	var e3 = _new_effect("", {"flow": {"type": "conditional", "condition": "attack_direction:flank"}})
	e3.else_effects = [e2]
	var main_ab = _new_ability("Holló Taktika", "Oldalról támadó egységeid +1 támadás, hátulról támadók +2 támadás és Ütéselőny.", t0, [t1], [e3])
	var card = CharacterCardScript.new()
	card.card_id = 1015
	card.card_name = "Gúner"
	card.card_class = "Zsivány"
	card.title = "a Holló"
	card.game_rules = {"diagonal_placement": true}
	card.description = "Átlósan is kijátszhatsz egységeket a meglévő egységeid mellé. Ha egy egységed oldalról támad, +1 támadás. Ha hátulról, +2 és Ütéselőnyt is kap."
	card.abilities = [main_ab]
	return card

static func _build_x_mizuki_kiralyno():
	var t0 = _new_trigger("CONTINUOUS")
	var main_ab = _new_ability("Korona Víztükre", "Tükörkép effektjeid egy választott szomszédos mezőre is hatnak.", t0, [], [])
	var card = CharacterCardScript.new()
	card.card_id = 1016
	card.card_name = "X. Mizuki Királynő"
	card.card_class = "Bölcs"
	card.title = "a Korona Víztükre"
	card.description = "A tükörkép effektjeid egy választott szomszédos mezőre is hatnak."
	card.abilities = [main_ab]
	return card

static func _build_nixie():
	var t0 = _new_trigger("ON_DEATH", {"modifier1": "ALLY", "limit_type": "PER_TURN", "limit_count": 1})
	var t1 = _new_target("Unit", "Ally", "Automatic", {"trigger_interactor": "KilledUnit"})
	var e2 = _new_effect("ExecuteAbility", {"parameters": {"AbilityType": "ON_DEATH"}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Halál Visszhangja", "Minden körben az első Halál effekted kétszer hat.", t0, [t1], [e2])
	var card = CharacterCardScript.new()
	card.card_id = 1017
	card.card_name = "Nixie"
	card.card_class = "Garabonciás"
	card.title = "a Boszorkánydoktor"
	card.description = "Minden körben az első Halál effekted kétszer hat."
	card.abilities = [main_ab]
	return card

static func _build_caecus():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var e2 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Csatakiáltás", "Húzz egy lapot!", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2001
	card.card_name = "Caecus"
	card.card_class = "Mágus"
	card.cost = 1
	card.attack = 1
	card.hp = 1
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Csatakiáltás: Húzz egy lapot!"
	card.abilities = [main_ab]
	return card

static func _build_matroz():
	var t0 = _new_trigger("ON_KILL")
	var t1 = _new_target("Card", "Any", "Automatic", {"trigger_interactor": "KilledUnit"})
	var e2 = _new_effect("ExecuteAbility", {"parameters": {"AbilityType": "ON_PLAY"}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Rablás", "Kijátszom az általam megölt egységek Csatakiáltását.", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2002
	card.card_name = "Matróz"
	card.card_class = "Harcos"
	card.card_class2 = "Zsivány"
	card.cost = 2
	card.attack = 3
	card.hp = 2
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Rablás: Kijátszom az általam megölt egységek Csatakiáltását."
	card.tags = ["Kalóz"]
	card.flavor_text = "A tengeren minden szabad préda."
	card.abilities = [main_ab]
	return card

static func _build_hektor():
	var card = UnitCardScript.new()
	card.card_id = 2003
	card.card_name = "Hektor"
	card.card_class = "Zsivány"
	card.cost = 1
	card.attack = 1
	card.hp = 3
	card.move_speed = 1
	card.attack_range = 1
	card.description = ""
	card.tags = ["Kalóz"]
	card.flavor_text = "Csak egy gályarab."
	return card

static func _build_barkakedvenc():
	var t0 = _new_trigger("ON_ATTACK", {"trigger_interactors": {"AttackedUnit": "damaged"}})
	var t1 = _new_target("Unit", "Ally", "Self")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "ATK", "ModifyAmount": 2, "ModifyDuration": 3}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Vérszomj", "Ha a célpont sérült, +2 Támadás a harc végéig.", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2004
	card.card_name = "Bárkakedvenc"
	card.card_class = "Zsivány"
	card.cost = 2
	card.attack = 1
	card.hp = 4
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Támadáskor: Ha a célpont sérült, +2 Támadás a harc végéig."
	card.tags = ["Kalóz", "Bestia"]
	card.flavor_text = "A legénység kedvence, az ellenség réme."
	card.abilities = [main_ab]
	return card

static func _build_pirato_sanchez():
	var t0 = _new_trigger("CONTINUOUS")
	var t1 = _new_target("Unit", "Ally", "AllValid", {"condition": "tag:Kalóz,adjacent"})
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "ATK", "ModifyAmount": 1, "ModifyDuration": 3}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Kalóz kapitány", "Szomszédos szövetséges Kalóz egységek +1 Támadást kapnak támadáskor.", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2005
	card.card_name = "Pirato Sanchez"
	card.card_class = "Zsivány"
	card.cost = 3
	card.attack = 3
	card.hp = 3
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Aura: Szomszédos szövetséges Kalóz egységek +1 Támadást kapnak támadáskor."
	card.tags = ["Kalóz"]
	card.flavor_text = "\"Minden kalóz testvér – amíg van rum.\""
	card.abilities = [main_ab]
	return card

static func _build_luna_kapitany():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Hand", "Ally", "Automatic")
	var e2 = _new_effect("Search", {"parameters": {"SearchFilters": "type:UNIT,tag:Kalóz,cost<5", "SelectAmount": 1, "Prompt": "Válassz Kalóz egységet!"}, "tag": "chosen", "target_ref": "targets[0]"})
	var e3 = _new_effect("Summon", {"target_ref": "chosen.SearchResults", "flow": {"type": "conditional", "condition": "count(chosen.SearchResults) > 0"}})
	var main_ab = _new_ability("Kalózok gyülekező!", "Idézz meg egy Kalóz egységet a kezedből, amelynek költsége kevesebb, mint 5!", t0, [t1], [e2, e3])
	var card = UnitCardScript.new()
	card.card_id = 2006
	card.card_name = "Luna kapitány"
	card.card_class = "Zsivány"
	card.cost = 5
	card.attack = 4
	card.hp = 4
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Csatakiáltás: Idézz meg egy Kalóz egységet a kezedből, amelynek költsége kevesebb, mint 5!"
	card.tags = ["Kalóz"]
	card.flavor_text = "A holdfény alatt minden hajó az övé."
	card.abilities = [main_ab]
	return card

static func _build_arnyekurno():
	var card = UnitCardScript.new()
	card.card_id = 2007
	card.card_name = "Árnyékúrnő"
	card.card_class = "Zsivány"
	card.cost = 7
	card.attack = 6
	card.hp = 4
	card.move_speed = 1
	card.attack_range = 2
	card.rarity = Card.Rarity.LEGENDARY
	card.description = "Lövéstáv 2."
	card.tags = ["Kalóz", "Csempész"]
	card.flavor_text = "Senki nem látja jönni, mindenki érzi menni."
	return card

static func _build_papagaj():
	var t0 = _new_trigger("ON_PLAY", {"modifier1": "ALLY", "modifier2": "Unit", "trigger_interactors": {"PlayedCard": "tag:Kalóz,not_self"}})
	var t1 = _new_target("Card", "Ally", "Automatic", {"trigger_interactor": "PlayedCard"})
	var e2 = _new_effect("Summon", {"parameters": {"SummonedEntity": "SELF_CARD", "SummonConstraint": "adjacent_to:PlayedUnit", "SummonPrompt": "Válassz szomszédos mezőt a Papagáj lehelyezéséhez!"}})
	var main_ab = _new_ability("Kalóz Kísérő", "Amikor kijátszol egy másik Kalózt, kijátszhatsz mellé körön kívül!", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2008
	card.card_name = "Papagáj"
	card.card_class = "Zsivány"
	card.card_class2 = "Vaják"
	card.cost = 1
	card.attack = 1
	card.hp = 1
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Amikor kijátszol egy másik Kalózt, kijátszhatsz mellé körön kívül!"
	card.tags = ["Állat", "Kalóz"]
	card.abilities = [main_ab]
	return card

static func _build_embercsempesz():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Deck", "Enemy", "Automatic")
	var e2 = _new_effect("Reveal", {"parameters": {"RevealAmount": 1}, "tag": "peeked", "target_ref": "targets[0]"})
	var e3 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "MyHand"}, "target_ref": "peeked.RevealedCards", "flow": {"type": "conditional", "condition": "peeked.RevealedCards[0].card_type == unit"}})
	var main_ab = _new_ability("Csempészés", "Nézd meg az ellenfeled paklijának felső lapját! Ha egység, rabold el!", t0, [t1], [e2, e3])
	var card = UnitCardScript.new()
	card.card_id = 2009
	card.card_name = "Embercsempész"
	card.card_class = "Zsivány"
	card.cost = 2
	card.attack = 2
	card.hp = 1
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Csatakiáltás: Nézd meg az ellenfeled paklijának felső lapját! Ha egység, rabold el!"
	card.tags = ["Csempész"]
	card.abilities = [main_ab]
	return card

static func _build_kapzsi_kisertet():
	var t0 = _new_trigger("ON_DEATH")
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var e2 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Kapzsiság", "Húzz egy lapot!", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2010
	card.card_name = "Kapzsi kísértet"
	card.card_class = "Garabonciás"
	card.cost = 1
	card.attack = 1
	card.hp = 1
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Halál: Húzz egy lapot!"
	card.tags = ["Élettelen"]
	card.abilities = [main_ab]
	return card

static func _build_ryan_cooper():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var e2 = _new_effect("Search", {"parameters": {"SearchFilters": "type:SPELL,cost<=2", "SelectAmount": 1, "Prompt": "Nevezz meg egy varázslatot!"}, "tag": "named_card", "target_ref": "targets[0]"})
	var ab0 = _new_ability("Varázslat Keresés", "Nevezz meg egy max. 2 költségű varázslatot a paklidból!", t0, [t1], [e2])
	var t3 = _new_trigger("ON_DEATH")
	var t4 = _new_target("Deck", "Ally", "Automatic")
	var t5 = _new_target("Deck", "Ally", "Automatic", {"condition": "tag:named_card"})
	var e6 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "MyHand"}})
	e6.inline_target = t5
	var ab1 = _new_ability("Emlék", "Húzd fel a megnevezett lapot!", t3, [t4], [e6])
	var card = UnitCardScript.new()
	card.card_id = 2011
	card.card_name = "Ryan Cooper"
	card.card_class = "Garabonciás"
	card.cost = 2
	card.attack = 2
	card.hp = 1
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Csatakiáltás: Nevezz meg egy max. 2 költségű varázslatot a paklidból! Halál: Húzd fel!"
	card.abilities = [ab0, ab1]
	return card

static func _build_bolyongo():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var e2 = _new_effect("Draw", {"parameters": {"DrawAmount": 2}, "tag": "drawn_cards", "target_ref": "targets[0]"})
	var t3 = _new_target("Card", "Ally", "PlayerChoice", {"condition": "in:drawn_cards.DrawnCard", "prompt": "Válassz lapot száműzésre!"})
	var e4 = _new_effect("Exile")
	e4.inline_target = t3
	var main_ab = _new_ability("Vándor Tudás", "Húzz 2 lapot és száműzd az egyiket!", t0, [t1], [e2, e4])
	var card = UnitCardScript.new()
	card.card_id = 2012
	card.card_name = "Bolyongó"
	card.card_class = "Garabonciás"
	card.cost = 3
	card.attack = 1
	card.hp = 2
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Csatakiáltás: Húzz 2 lapot és száműzd az egyiket!"
	card.tags = ["Élettelen"]
	card.abilities = [main_ab]
	return card

static func _build_ouroboros():
	var t0 = _new_trigger("ON_DEATH")
	var t1 = _new_target("Card", "Ally", "Automatic", {"trigger_interactor": "played_card"})
	var e2 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "MyHand"}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Élettelen Sárkány", "Halál: Visszakerülök az engem kontrolláló játékos kezébe.", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2013
	card.card_name = "Ouroboros"
	card.card_class = "Garabonciás"
	card.cost = 7
	card.attack = 7
	card.hp = 7
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Halál: Visszakerülök az engem kontrolláló játékos kezébe."
	card.tags = ["Sárkány", "Élettelen"]
	card.abilities = [main_ab]
	return card

static func _build_hjaflgar():
	var t0 = _new_trigger("ON_ATTACK_KILL", {"modifier1": "ALLY", "modifier2": "Unit"})
	var t1 = _new_target("Card", "Ally", "Self")
	var t2 = _new_target("Unit", "Enemy", "Random", {"condition": "nearest_to:killed_unit"})
	var e3 = _new_effect("DealDamage", {"parameters": {"DamageAmount": "overkill"}})
	e3.inline_target = t2
	var main_ab = _new_ability("Hasítás", "Ha támadással ölsz meg egy ellenségest, a sebzéstöbblet megsebzi a legközelebbi ellenséget.", t0, [t1], [e3])
	var card = CharacterCardScript.new()
	card.card_id = 2014
	card.card_name = "Hjaflgar"
	card.card_class = "Harcos"
	card.title = "a Havasi Haramia"
	card.description = "Miután egy szövetséges egységed támadással megöl egy ellenséges egységet, a sebzéstöbblet megsebzi a legközelebbi ellenséget."
	card.abilities = [main_ab]
	return card

static func _build_mashu_liderc():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Any", "Automatic")
	var e2 = _new_effect("ModifyKeyword", {"parameters": {"AddedKeywords": ["Kábítás"], "NewKeywordDurations": 2}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Tükör Kábítás", "Kábítsd el a tükörképemen álló egységet a következő köröm végéig.", t0, [t1], [e2])
	var card = UnitCardScript.new()
	card.card_id = 2015
	card.card_name = "Mashu lidérc"
	card.card_class = "Bölcs"
	card.cost = 2
	card.attack = 2
	card.hp = 3
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Csatakiáltás: Kábítsd el a tükörképemen álló egységet a következő köröm végéig!"
	card.tags = ["Dinasztikus", "Lidérc"]
	card.flavor_text = "A víztükörben csak az árnyéka mozdul."
	card.abilities = [main_ab]
	return card

static func _build_ambiciosus_paleontologus():
	var t0 = _new_trigger("ON_DEATH")
	var t1 = _new_target("Player", "Ally", "Automatic")
	var e2 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "PermanentNamed", "ModifyAmount": 1}, "target_ref": "targets[0]"})
	var e3 = _new_effect("", {"flow": {"type": "conditional", "condition": "counter(paleontologus_asatas)>=4"}})
	var main_ab = _new_ability("Ásatás", "Halál: +1 permanens jelző. 4 jelzőnél: törlés, Őshüllő a kezedbe 0 költséggel.", t0, [t1], [e2, e3])
	var card = UnitCardScript.new()
	card.card_id = 2016
	card.card_name = "Ambíciózus paleontológus"
	card.card_class = "Garabonciás"
	card.cost = 3
	card.attack = 1
	card.hp = 2
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Halál: Tegyél egy permanens jelzőt az Ambíciózus paleontológus lapokra. Ha összesen legalább 4 jelző van, töröld őket, és tedd a kezedbe az Őshüllőt 0 költséggel!"
	card.abilities = [main_ab]
	return card

static func _build_oshullo():
	var card = UnitCardScript.new()
	card.card_id = 2017
	card.card_name = "Őshüllő"
	card.card_class = "Garabonciás"
	card.cost = 7
	card.attack = 7
	card.hp = 7
	card.move_speed = 1
	card.attack_range = 1
	card.description = "Segéd egység — nem gyűjthető, csak az Ambíciózus paleontológus képessége hozza létre."
	card.tags = ["Segéd", "Sárkány", "Élettelen"]
	return card

static func _build_explar():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Entity", "Any", "PlayerChoice", {"target_range": 2})
	var e2 = _new_effect("DealDamage", {"parameters": {"DamageAmount": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Tűzlövedék", "Sebezz 1 életerőt!", t0, [t1], [e2])
	var card = SpellCardScript.new()
	card.card_id = 3001
	card.card_name = "Explar"
	card.card_class = "Mágus"
	card.cost = 1
	card.spell_range = 2
	card.school = "Tűz"
	card.description = "Sebezz 1 életerőt!"
	card.tags = ["Tűz"]
	card.abilities = [main_ab]
	return card

static func _build_tor():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Ally", "PlayerChoice")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "ATK", "ModifyAmount": 1, "ModifyDuration": 0}, "target_ref": "targets[0]"})
	var e3 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "MyHand"}, "target_ref": "SELF_CARD"})
	var e4 = _new_effect("Attach", {"target_ref": "targets[0]"})
	e4.sub_effects = [e3]
	var main_ab = _new_ability("Tőr", "A célpont +1 Támadást kap. Ha az egység meghal, a Tőr visszakerül a kezedbe.", t0, [t1], [e2, e4])
	var card = SpellCardScript.new()
	card.card_id = 3002
	card.card_name = "Tőr"
	card.card_class = "Zsivány"
	card.cost = 1
	card.description = "+1 Támadás egy szövetséges egységnek. Ha az egység meghal, a Tőr visszakerül a kezedbe."
	card.tags = ["Fegyver"]
	card.abilities = [main_ab]
	return card

static func _build_mozgositas():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Hand", "Ally", "Automatic")
	var e2 = _new_effect("Search", {"parameters": {"SearchFilters": "type:UNIT,cost<=1", "SelectAmount": 1, "Prompt": "Válassz egységet lehelyezéshez!"}, "tag": "mob_chosen", "target_ref": "targets[0]"})
	var e3 = _new_effect("Summon", {"target_ref": "mob_chosen.SearchResults", "flow": {"type": "conditional", "condition": "count(mob_chosen.SearchResults) > 0"}})
	var e4 = _new_effect("", {"flow": {"type": "repeat", "count": 2}})
	e4.sub_effects = [e2, e3]
	var main_ab = _new_ability("Mozgósítás", "Idézz meg legfeljebb 2 egységet a kezedből, amelyek költsége egyenként 1.", t0, [t1], [e4])
	var card = SpellCardScript.new()
	card.card_id = 3003
	card.card_name = "Mozgósítás"
	card.card_class = "Harcos"
	card.cost = 1
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Idézz meg legfeljebb 2 egységet a kezedből, amelyek költsége egyenként 1."
	card.abilities = [main_ab]
	return card

static func _build_villamhaboru():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Ally", "AllValid")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "MOVE_SPEED", "ModifyAmount": 2, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var e3 = _new_effect("ModifyKeyword", {"parameters": {"AddedKeywords": ["Roham"], "NewKeywordDurations": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Villámháború", "Minden szövetséges egység +2 Mozgási sebességet és Roham kulcsszót kap ebben a körben.", t0, [t1], [e2, e3])
	var card = SpellCardScript.new()
	card.card_id = 3004
	card.card_name = "Villámháború"
	card.card_class = "Harcos"
	card.cost = 2
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.spell_range = 0
	card.description = "Minden szövetséges egység +2 Mozgási sebességet és Roham kulcsszót kap ebben a körben."
	card.abilities = [main_ab]
	return card

static func _build_gyorshitel():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Player", "Ally", "Automatic")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "ModifyAmount": -2, "ApplyFilter": "next_card", "ModifyDuration": 4}, "target_ref": "targets[0]"})
	var e3 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Mana", "ModifyAmount": -2}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Gyorshitel", "A következő lapod 2-vel kevesebbe kerül. A következő körödben -2 elérhető mana.", t0, [t1], [e2, e3])
	var card = SpellCardScript.new()
	card.card_id = 3005
	card.card_name = "Gyorshitel"
	card.card_class = "Zsivány"
	card.cost = 0
	card.description = "A következő lapod 2-vel kevesebbe kerül. A következő körödben -2 elérhető mana."
	card.flavor_text = "\"Csak aláírd itt... és itt... és itt.\""
	card.abilities = [main_ab]
	return card

static func _build_lesbol_tamadas():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Ally", "PlayerChoice")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "MOVE_SPEED", "ModifyAmount": 1, "ModifyDuration": 1}, "target_ref": "targets[0]"})
	var e3 = _new_effect("ModifyKeyword", {"parameters": {"AddedKeywords": ["Ütéselőny"], "NewKeywordDurations": 1}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Lesből támadás", "Egy szövetséges egység +1 Mozgási sebességet és Ütéselőnyt kap ebben a körben.", t0, [t1], [e2, e3])
	var card = SpellCardScript.new()
	card.card_id = 3006
	card.card_name = "Lesből támadás"
	card.card_class = "Zsivány"
	card.cost = 3
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Egy szövetséges egység +1 Mozgási sebességet és Ütéselőnyt kap ebben a körben."
	card.abilities = [main_ab]
	return card

static func _build_ujraelosztas():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Hand", "Enemy", "Automatic")
	var t2 = _new_target("Card", "Enemy", "PlayerChoice", {"prompt": "Válassz lapot az ellenfél kezéből!"})
	var e3 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "MyHand"}, "target_ref": "targets[0]"})
	e3.inline_target = t2
	var e4 = _new_effect("", {"flow": {"type": "repeat_while", "condition": "enemy_hand_count > my_hand_count"}})
	e4.sub_effects = [e3]
	var main_ab = _new_ability("Újraelosztás", "Rablás: Válassz lapokat az ellenfél kezéből, amíg nem lesz több lapja, mint neked.", t0, [t1], [e4])
	var card = SpellCardScript.new()
	card.card_id = 3007
	card.card_name = "Újraelosztás"
	card.card_class = "Zsivány"
	card.cost = 5
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Rablás: Válassz lapokat az ellenfél kezéből, amíg nem lesz több lapja, mint neked."
	card.flavor_text = "\"Ami a tiéd, az az enyém. Ami az enyém, az is az enyém.\""
	card.abilities = [main_ab]
	return card

static func _build_hatarzar():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Player", "Enemy", "Automatic")
	var e2 = _new_effect("ModifyStat", {"parameters": {"ModifiedStat": "COST", "ModifyAmount": 2, "ApplyFilter": "type:UNIT", "ModifyDuration": 2}, "target_ref": "targets[0]"})
	var main_ab = _new_ability("Határzár", "Az ellenfeled következő körében minden egység +2-vel többe kerül neki.", t0, [t1], [e2])
	var card = SpellCardScript.new()
	card.card_id = 3008
	card.card_name = "Határzár"
	card.card_class = "Harcos"
	card.cost = 4
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Az ellenfeled következő körében minden egység +2-vel többe kerül neki."
	card.flavor_text = "\"Innentől senki se megy sehová.\""
	card.abilities = [main_ab]
	return card

static func _build_all_in():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Hand", "Ally", "Automatic")
	var t2 = _new_target("Player", "Ally", "Automatic")
	var t3 = _new_target("Deck", "Ally", "Automatic")
	var e4 = _new_effect("Search", {"parameters": {"SearchFilters": "type:SPELL"}, "tag": "spell_count", "target_ref": "targets[0]"})
	var e5 = _new_effect("Search", {"parameters": {"SearchFilters": "type:UNIT"}, "tag": "unit_count", "target_ref": "targets[0]"})
	var e6 = _new_effect("Discard", {"parameters": {"DiscardFilters": "all"}, "target_ref": "targets[0]"})
	var e7 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Mana", "ModifyAmount": "count(spell_count.SearchResults)"}, "target_ref": "targets[1]"})
	var e8 = _new_effect("Draw", {"parameters": {"DrawAmount": "count(unit_count.SearchResults)"}, "target_ref": "targets[2]"})
	var main_ab = _new_ability("All in", "Dobd el a kezed. Varázslatonként 1 manát kapsz, egységenként 1 lapot húzol.", t0, [t1, t2, t3], [e4, e5, e6, e7, e8])
	var card = SpellCardScript.new()
	card.card_id = 3009
	card.card_name = "All in"
	card.card_class = "Zsivány"
	card.cost = 0
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Dobd el a kezed. Az eldobott varázslatok számával egyező manát kapsz erre a körre, és az eldobott egységek számával egyező lapot húzol."
	card.abilities = [main_ab]
	return card

static func _build_lomtalanitas():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Deck", "Ally", "Automatic")
	var e2 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}, "target_ref": "targets[0]"})
	var t3 = _new_target("Card", "Ally", "PlayerChoice", {"prompt": "Dobj el egy lapot!"})
	var e4 = _new_effect("Discard", {"parameters": {"DiscardAmount": 1}})
	e4.inline_target = t3
	var main_ab = _new_ability("Lomtalanítás", "Húzz egy lapot, majd dobj el egyet!", t0, [t1], [e2, e4])
	var card = SpellCardScript.new()
	card.card_id = 3010
	card.card_name = "Lomtalanítás"
	card.card_class = "Garabonciás"
	card.cost = 0
	card.description = "Húzz egy lapot, majd dobj el egyet a kezedből!"
	card.abilities = [main_ab]
	return card

static func _build_hamiskartya():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Deck", "Enemy", "Automatic")
	var t2 = _new_target("Card", "Ally", "Self")
	var e3 = _new_effect("Draw", {"parameters": {"DrawAmount": 1}, "tag": "stolen", "target_ref": "targets[0]"})
	var e4 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "EnemyHand"}, "target_ref": "targets[1]"})
	var main_ab = _new_ability("Hamiskártya", "Rablás: Húzz egyet az ellenfél paklijából és add neki ezt a lapot cserébe!", t0, [t1, t2], [e3, e4])
	var card = SpellCardScript.new()
	card.card_id = 3011
	card.card_name = "Hamiskártya"
	card.card_class = "Zsivány"
	card.cost = 1
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.spell_range = 0
	card.description = "Rablás: Húzd el az ellenfél paklijának felső lapját és add neki ezt a varázslatot cserébe!"
	card.abilities = [main_ab]
	return card

static func _build_elcsenes():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Enemy", "PlayerChoice", {"target_range": 1, "prompt": "Válassz ellenséges egységet!"})
	var t2 = _new_target("Unit", "Ally", "PlayerChoice", {"prompt": "Válassz szövetségest a gyűrű áthelyezéséhez!"})
	var e3 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Ring", "ModifyAmount": -1}, "target_ref": "targets[0]"})
	var e4 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Ring", "ModifyAmount": 1}, "target_ref": "targets[1]"})
	var main_ab = _new_ability("Elcsenés", "Rabolj el egy gyűrűt egy ellenséges egységről és helyezd egy szövetségesre!", t0, [t1, t2], [e3, e4])
	var card = SpellCardScript.new()
	card.card_id = 3012
	card.card_name = "Elcsenés"
	card.card_class = "Zsivány"
	card.cost = 1
	card.spell_range = 1
	card.description = "Rabolj el egy gyűrűt egy ellenséges egységről és helyezd egy szövetségesre!"
	card.abilities = [main_ab]
	return card

static func _build_arurakodas():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Hand", "Ally", "Automatic")
	var t2 = _new_target("Hand", "Enemy", "Automatic")
	var t3 = _new_target("Card", "Ally", "OpponentChoice", {"prompt": "Az ellenfél választ egy lapot a kezedből!"})
	var e4 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "EnemyHand"}, "target_ref": "targets[0]"})
	e4.inline_target = t3
	var t5 = _new_target("Card", "Enemy", "PlayerChoice", {"prompt": "Válassz lapot az ellenfél kezéből!"})
	var e6 = _new_effect("MoveToZone", {"parameters": {"GoalZone": "MyHand"}, "target_ref": "targets[1]"})
	e6.inline_target = t5
	var main_ab = _new_ability("Árurakodás", "Mindkét játékos felfedi a kezét. Az ellenfeled elrabol egy lapot, majd te egyet az övéből!", t0, [t1, t2], [e4, e6])
	var card = SpellCardScript.new()
	card.card_id = 3013
	card.card_name = "Árurakodás"
	card.card_class = "Zsivány"
	card.cost = 2
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Mindkét játékos felfedi a kezét. Az ellenfeled elrabol egy lapot a kezedből, majd te egyet az övéből!"
	card.abilities = [main_ab]
	return card

static func _build_rozzant_granat():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Ally", "PlayerChoice", {"prompt": "Válassz szövetségest!"})
	var t2 = _new_target("Unit", "Enemy", "PlayerChoice", {"condition": "adjacent_to:targets[0]", "prompt": "Válassz szomszédos ellenséget!"})
	var e3 = _new_effect("Kill")
	e3.inline_target = t2
	var e4 = _new_effect("Kill", {"target_ref": "targets[0]"})
	var e5 = _new_effect("Kill", {"target_ref": "targets[0]"})
	var e6 = _new_effect("", {"flow": {"type": "conditional", "condition": "has_adjacent_enemy(targets[0])"}})
	e6.sub_effects = [e3, e4]
	e6.else_effects = [e5]
	var main_ab = _new_ability("Rozzant gránát", "Ölj meg egy szövetségest és egy vele szomszédos ellenségest!", t0, [t1], [e6])
	var card = SpellCardScript.new()
	card.card_id = 3014
	card.card_name = "Rozzant gránát"
	card.card_class = "Zsivány"
	card.cost = 2
	card.spell_type = SpellCardScript.SpellType.RITUAL
	card.description = "Ölj meg egy szövetségest és egy vele szomszédos ellenségest!"
	card.abilities = [main_ab]
	return card

static func _build_suttogavatas():
	var t0 = _new_trigger("ON_PLAY")
	var t1 = _new_target("Unit", "Ally", "PlayerChoice", {"prompt": "Válassz egy szövetséges egységet az újraidézéshez!"})
	var e2 = _new_effect("StoreRef")
	var e3 = _new_effect("StoreRef")
	var e4 = _new_effect("Kill", {"target_ref": "targets[0]"})
	var e5 = _new_effect("Summon", {"parameters": {"SummonedEntity": "ref/sacrifice_card", "SummoningTile": "ref/sacrifice_tile"}})
	var main_ab = _new_ability("Suttogóavatás", "Áldozz fel egy szövetségest, majd egyből idézd újra ugyanazon a mezőn.", t0, [t1], [e2, e3, e4, e5])
	var card = SpellCardScript.new()
	card.card_id = 3015
	card.card_name = "Suttogóavatás"
	card.card_class = "Garabonciás"
	card.cost = 1
	card.spell_range = 0
	card.description = "Áldozz fel egy szövetségest, majd egyből idézd újra ugyanazon a mezőn!"
	card.tags = ["Nekromancia"]
	card.abilities = [main_ab]
	return card

static func _build_a_gomb():
	var t0 = _new_trigger("ON_DEATH")
	var t1 = _new_target("Card", "Ally", "Self")
	var e2 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Charge", "ModifyAmount": 1, "MaxCount": 12}, "target_ref": "targets[0]"})
	var ab0 = _new_ability("Töltés", "Amikor egy egység meghal, +1 számláló (max. 12).", t0, [t1], [e2])
	var t3 = _new_trigger("ON_COUNTER_COUNT", {"parameters": {"CounterType": "Charge", "CounterCount": 12}})
	var t4 = _new_target("Unit", "Ally", "PlayerChoice", {"prompt": "Válassz egységet a Sérthetetlen pajzshoz!"})
	var e5 = _new_effect("ModifyKeyword", {"parameters": {"AddedKeywords": ["Sérthetetlen"], "NewKeywordDurations": 0}, "target_ref": "targets[0]"})
	var e6 = _new_effect("Exile", {"target_ref": "SELF_CARD"})
	var e7 = _new_effect("Attach", {"target_ref": "targets[0]"})
	e7.sub_effects = [e6]
	var ab1 = _new_ability("Sérthetetlen Pajzs", "Ha 12 számláló van rajta: csatolj egy szövetségeshez és tedd Sérthetetlenné!", t3, [t4], [e5, e7])
	var t8 = _new_trigger("ON_PROTECTION_TRIGGERED")
	var t9 = _new_target("Card", "Ally", "Self")
	var e10 = _new_effect("ModifyCounter", {"parameters": {"CounterType": "Charge", "ModifyAmount": -2}, "target_ref": "targets[0]"})
	var e11 = _new_effect("Exile", {"target_ref": "targets[0]"})
	var e12 = _new_effect("", {"flow": {"type": "conditional", "condition": "self_counter >= 2"}})
	e12.sub_effects = [e10]
	e12.else_effects = [e11]
	var ab2 = _new_ability("Pajzs Kopás", "Valahányszor a védett egységet védelem megakadályoz, -2 számláló. Ha nem tud, a Gömb megsemmisül.", t8, [t9], [e12])
	var card = SpellCardScript.new()
	card.card_id = 4001
	card.card_name = "A Gömb"
	card.card_class = "Mítikus"
	card.cost = 0
	card.card_type = Card.CardType.ARTIFACT
	card.description = "Amikor egy egység meghal, tegyél rám egy számlálót (max. 12). Amikor 12 számláló van rajtam, kijelölhetsz egy szövetséges egységet. Amíg játékban vagyok, az az egység Sérthetetlen.

Valahányszor ez az egység sebződne, meghalna, megsemmisülne vagy elhagyná az arénát, távolíts el 2 számlálót rólam. Ha így nem tudsz 2 számlálót eltávolítani, semmisíts meg!"
	card.abilities = [ab0, ab1, ab2]
	return card
